import { ShowModel } from '../../model';
import Formation from '../../assets/images/01.jpg';
import Two from '../../assets/images/02.jpg';
import Three from '../../assets/images/03.jpg';
import LailaDream from '../../assets/images/04.jpg';

export const dataList: ShowModel[] = [
  {
    id: 1,
    name: { ar: 'التشكيلة', en: `Formation` },
    theater_id: 1,
    cast_name: 'المعهد العالي للفنون المسرحية',
    show_date: '20-Sep-2024',
    show_time: '7:00 PM',
    booking_available: false,
    theater_name: 'الملعب',
    link: '',
    poster: Formation,
    author: 'أحمد سمير',
    director: 'مروان جاسور',
  },
  {
    id: 2,
    name: { ar: 'يوميات ممثل مهزوم', en: `Diaries of a loser actor` },
    theater_id: 1,
    cast_name: 'المعهد العالي للفنون المسرحية',
    show_date: '22-Sep-2024',
    show_time: '8:00 PM',
    booking_available: true,
    theater_name: 'القاعة الدائرية',
    link: '',
    poster: Two,
    author: 'عصام نابيل',
    director: 'مطر زايد',
  },
  {
    id: 3,
    name: { ar: 'ع السلم', en: `Laila's dream` },
    theater_id: 1,
    cast_name: 'المعهد العالي للفنون المسرحية',
    show_date: '22-Sep-2024',
    show_time: '8:00 PM',
    booking_available: true,
    theater_name: 'القاعة الدائرية',
    link: '',
    poster: Three,
    author: 'حسام سيد',
    director: 'أحمد بيرسي',
  },
  {
    id: 4,
    name: { ar: 'حلم ليلى', en: `Laila's dream` },
    theater_id: 1,
    cast_name: 'المعهد العالي للفنون المسرحية',
    show_date: '22-Sep-2024',
    show_time: '8:00 PM',
    booking_available: true,
    theater_name: 'القاعة الدائرية',
    link: '',
    poster: LailaDream,
    author: 'سعد الله ونّوس',
    director: 'ليديا فاروق',
  },
  {
    id: 5,
    name: { ar: 'حلم ليلى', en: `Laila's dream` },
    theater_id: 1,
    cast_name: 'المعهد العالي للفنون المسرحية',
    show_date: '22-Sep-2024',
    show_time: '8:00 PM',
    booking_available: true,
    theater_name: 'القاعة الدائرية',
    link: '',
    poster: '',
    author: 'سعد الله ونّوس',
    director: 'ليديا فاروق',
  },
];
